#!/usr/bin/env bash
# script to display domain and subdomain with record type in a format

display_ans ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk { printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk { printf $5 }'
    echo ""
}

if [ "$#" -eq 2]; then
	display_ans "$1" "$2"
else
	for subs in "www" "lb-01" "web-01" "web-02"
	do
	display_ans "$1" "$subs"
	done
fi
