#!/usr/bin/env bash
# a Bash script to install Nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 777 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/location \/ {/a \
    location /redirect_me { \
        return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4'; \
    }' /etc/nginx/sites-available/default
sudo service nginx restart
