#!/usr/bin/env bash
# redirection configured to "301 Moved Permanently"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
sudo sed -i '/index index.html index.htm index.nginx-debian.html;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/;\
    }' /etc/nginx/sites-enabled/default


service nginx restart
