#!/usr/bin/env bash
# config Nginx and add HTTP header X-Served-By $HOSTNAME

# Install nginx on server
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create index page
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled/default
sudo chmod -R 777 /etc/nginx/sites-enabled/default

# Create error page
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html


# Add a page redirection to configuration file
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
# Add the header to know which server is used
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
