#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument

#get IP ADDRESS
IP_ADDRESS="${1}"

#get file name
file_name=$(basename $0)

#apply the condition

if ! [ "$IP_ADDRESS" ]
then
	echo "Usage: ${file_name} ${IP_ADDRESS}"
else
	ping -c 5 "${IP_ADDRESS}"
fi
