#!/usr/bin/env bash
# Make Nginx running and listen to port 80

sudo apt-get update
sudo apt-get -y install curl
sudo rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
