#!/usr/bin/env bash
# Make Nginx running and listen to port 80

# Install curl
sudo apt-get update
sudo apt-get -y install curl

# Modify Nginx configuration
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

