#!/usr/bin/env bash
# Make Nginx up and listen to port 80 and
# service (init) must say that nginx is not running

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
rm /run/nginx.pid
