#!/usr/bin/env bash
# Make Nginx up and listen to port 80 and
# service (init) must say that nginx is not running

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
