#!/usr/bin/env bash
# Make Nginx up and listen to port 80 and
# service (init) must say that nginx is not running

rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
echo "Hello" > /run/nginx.pid
echo "Hello" > /var/run/nginx.pid
