#!/usr/bin/env bash
#Bash script that displays a list of currently running processes
#shows all processes, for all users, including those which might not have a TTY
#Displays in a user-oriented format
#Shows process hierarchy

ps aux --forest
