#!/usr/bin/env bash
#displays lines containing word bash to get the PID of your Bash process
# shellcheck disable=SC2009
#script that displays the PID, along with the process name,
#of processes whose name contain the word bash

pgrep -l bash
