#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely
#In between each iteration of the loop, it sleeps 2 seconds

while [ 1 -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
