#!/usr/bin/env bash
#display the string "Best School" 10 times
#in no 4 display bad luck and in 8 display good luck

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
