#!/usr/bin/env bash
#display the string "Best School" 20 times
#use case for no 4, 9 and 17

i=0
while [ $i -lt 20 ]
do
	echo $i
	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
done
